before_install:
  - "./travis/before_install.sh"
install:
  - "./travis/install.sh"
script:
  - "mkdir build && cd build"
  - "cmake -DCMAKE_BUILD_TYPE=Release -DTWINE_USE_CXX11=${TWINE_USE_CXX11} .."
  - "make testsuite && ./testsuite"
os:
  - linux
  - osx
env:
  - CXX=g++ CC=gcc TWINE_USE_CXX11=ON
  - CXX=clang++ CC=clang TWINE_USE_CXX11=ON
  - CXX=g++ CC=gcc TWINE_USE_CXX11=OFF
  - CXX=clang++ CC=clang TWINE_USE_CXX11=OFF
